# Build on push and PR events
on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - run: |
          sudo apt update
          sudo apt install g++-mingw-w64
          cd LMS/windows
          make GXX=x86_64-w64-mingw32-g++ WINDRES=x86_64-w64-mingw32-windres
          cd ../../Scope/windows
          make GXX=x86_64-w64-mingw32-g++ WINDRES=x86_64-w64-mingw32-windres
          cd ../../SigGen/windows
          make GXX=x86_64-w64-mingw32-g++ WINDRES=x86_64-w64-mingw32-windres
          cd ../../SLMS/windows
          make GXX=x86_64-w64-mingw32-g++ WINDRES=x86_64-w64-mingw32-windres
